/**
 * Mock data для отображения контента при недоступности AppWrite.
 * Используется как fallback в freelance-db.
 */
import type { Category, Freelancer, Gig, Review } from '../types';

const pkg = (
  name: string,
  price: number,
  days: number,
  desc: string,
  features: string[]
) => ({ name, price, deliveryDays: days, description: desc, features });

const avatars: Record<string, string> = {
  alexdev: 'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=150',
  marinaui: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150',
  botmaster: 'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150',
  aianna: 'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
  mobilenik: 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=150',
  backendpro: 'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=150',
  webdesigner: 'https://images.pexels.com/photos/1065084/pexels-photo-1065084.jpeg?auto=compress&cs=tinysrgb&w=150',
  datamagic: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=150',
};

export const MOCK_CATEGORIES: Category[] = [
  { slug: 'web-development', name: 'Разработка сайтов', icon: 'Globe', gigCount: 3, description: 'Лендинги, корпоративные сайты' },
  { slug: 'mobile-apps', name: 'Мобильные приложения', icon: 'Smartphone', gigCount: 1, description: 'iOS, Android' },
  { slug: 'bots-automation', name: 'Боты и автоматизация', icon: 'Bot', gigCount: 2, description: 'Telegram, Discord боты' },
  { slug: 'ai-integrations', name: 'AI Интеграции', icon: 'Brain', gigCount: 2, description: 'ChatGPT, RAG-системы' },
  { slug: 'frontend', name: 'Frontend', icon: 'Layout', gigCount: 4, description: 'React, Vue, вёрстка' },
  { slug: 'backend', name: 'Backend', icon: 'Server', gigCount: 1, description: 'API, микросервисы' },
  { slug: 'databases', name: 'Базы данных', icon: 'Database', gigCount: 1, description: 'PostgreSQL, MongoDB' },
  { slug: 'mvp', name: 'Вайб-кодинг MVP', icon: 'Rocket', gigCount: 1, description: 'Быстрый запуск продукта' },
];

export const MOCK_FREELANCERS: Freelancer[] = [
  { id: 'fl_user_1', username: 'alexdev', name: 'Александр Петров', avatar: avatars.alexdev, title: 'Full-Stack Вайб-Кодер', rating: 4.9, reviewCount: 127, ordersCompleted: 253, responseTime: '~30 мин', isOnline: true, location: 'Москва', memberSince: 'Март 2024', bio: 'Создаю веб-приложения с AI-инструментами.', skills: ['React', 'Next.js', 'TypeScript'], successRate: 98, level: 'pro' },
  { id: 'fl_user_2', username: 'marinaui', name: 'Марина Козлова', avatar: avatars.marinaui, title: 'UI/UX Дизайнер + Фронтенд', rating: 4.8, reviewCount: 89, ordersCompleted: 156, responseTime: '~1 час', isOnline: true, location: 'Санкт-Петербург', memberSince: 'Январь 2024', bio: 'Figma + React + AI.', skills: ['Figma', 'React', 'Tailwind'], successRate: 97, level: 'verified' },
  { id: 'fl_user_3', username: 'botmaster', name: 'Дмитрий Волков', avatar: avatars.botmaster, title: 'Telegram & Discord Боты', rating: 4.7, reviewCount: 64, ordersCompleted: 98, responseTime: '~2 часа', isOnline: false, location: 'Казань', memberSince: 'Июнь 2024', bio: 'Разрабатываю ботов для Telegram и Discord.', skills: ['Python', 'Node.js', 'Telegram API'], successRate: 95, level: 'verified' },
  { id: 'fl_user_4', username: 'aianna', name: 'Анна Сергеева', avatar: avatars.aianna, title: 'AI-Интеграции', rating: 5.0, reviewCount: 42, ordersCompleted: 67, responseTime: '~45 мин', isOnline: true, location: 'Новосибирск', memberSince: 'Сентябрь 2024', bio: 'Интегрирую AI в бизнес-процессы.', skills: ['Python', 'OpenAI API', 'LangChain'], successRate: 100, level: 'pro' },
  { id: 'fl_user_5', username: 'mobilenik', name: 'Николай Ростов', avatar: avatars.mobilenik, title: 'Мобильная разработка', rating: 4.6, reviewCount: 38, ordersCompleted: 51, responseTime: '~3 часа', isOnline: false, location: 'Екатеринбург', memberSince: 'Ноябрь 2024', bio: 'React Native и Flutter.', skills: ['React Native', 'Flutter', 'TypeScript'], successRate: 94, level: 'verified' },
  { id: 'fl_user_6', username: 'backendpro', name: 'Игорь Кузнецов', avatar: avatars.backendpro, title: 'Backend & DevOps', rating: 4.8, reviewCount: 71, ordersCompleted: 112, responseTime: '~1 час', isOnline: true, location: 'Москва', memberSince: 'Февраль 2024', bio: 'API, базы данных, DevOps.', skills: ['Node.js', 'PostgreSQL', 'Docker'], successRate: 96, level: 'pro' },
  { id: 'fl_user_7', username: 'webdesigner', name: 'Елена Морозова', avatar: avatars.webdesigner, title: 'Веб-дизайн и Вёрстка', rating: 4.9, reviewCount: 95, ordersCompleted: 189, responseTime: '~40 мин', isOnline: true, location: 'Краснодар', memberSince: 'Декабрь 2023', bio: 'Стильные и конверсионные сайты.', skills: ['HTML', 'CSS', 'Figma'], successRate: 99, level: 'pro' },
  { id: 'fl_user_8', username: 'datamagic', name: 'Павел Новиков', avatar: avatars.datamagic, title: 'Базы данных и Аналитика', rating: 4.7, reviewCount: 33, ordersCompleted: 45, responseTime: '~2 часа', isOnline: false, location: 'Самара', memberSince: 'Май 2024', bio: 'Проектирую БД, оптимизирую запросы.', skills: ['PostgreSQL', 'MongoDB', 'Redis'], successRate: 93, level: 'verified' },
];

const flMap: Record<string, Freelancer> = {};
MOCK_FREELANCERS.forEach((f) => { flMap[f.username] = f; });

export const MOCK_GIGS: Gig[] = [
  {
    id: 'gig_1',
    title: 'Создам современный лендинг на Next.js за 2 дня',
    shortDescription: 'Быстрый и адаптивный лендинг с анимациями',
    description: 'Создам современный лендинг на Next.js 14 с Tailwind CSS и Framer Motion.',
    image: 'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=600',
    images: ['https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=600'],
    freelancer: flMap.alexdev,
    rating: 4.9,
    reviewCount: 127,
    ordersCount: 253,
    tags: ['Next.js', 'React', 'TypeScript', 'Tailwind'],
    category: 'Разработка сайтов',
    categorySlug: 'web-development',
    isFeatured: true,
    packages: {
      economy: pkg('Эконом', 2000, 3, 'Одностраничный лендинг', ['1 страница', 'Адаптивность']),
      standard: pkg('Стандарт', 5000, 5, 'Лендинг + доп. секции', ['До 5 секций', 'SEO']),
      premium: pkg('Премиум', 12000, 7, 'Полный лендинг + CMS', ['Безлимит секций', 'CMS']),
    },
  },
  {
    id: 'gig_2',
    title: 'Telegram бот для бизнеса с AI-ассистентом',
    shortDescription: 'Умный Telegram-бот с интеграцией ChatGPT',
    description: 'Разработаю Telegram-бота с AI-ассистентом на базе GPT.',
    image: 'https://images.pexels.com/photos/5926382/pexels-photo-5926382.jpeg?auto=compress&cs=tinysrgb&w=600',
    images: ['https://images.pexels.com/photos/5926382/pexels-photo-5926382.jpeg?auto=compress&cs=tinysrgb&w=600'],
    freelancer: flMap.botmaster,
    rating: 4.7,
    reviewCount: 64,
    ordersCount: 98,
    tags: ['Python', 'Telegram', 'ChatGPT', 'API'],
    category: 'Боты и автоматизация',
    categorySlug: 'bots-automation',
    isFeatured: true,
    packages: {
      economy: pkg('Эконом', 3000, 3, 'Простой бот', ['До 10 команд']),
      standard: pkg('Стандарт', 8000, 5, 'Бот с AI', ['AI-ответы', 'Админ-панель']),
      premium: pkg('Премиум', 20000, 10, 'Полный AI-бот', ['CRM интеграция', 'Оплата']),
    },
  },
  {
    id: 'gig_3',
    title: 'React дашборд с графиками и аналитикой',
    shortDescription: 'Интерактивный дашборд на React',
    description: 'Создам профессиональный дашборд с интерактивными графиками.',
    image: 'https://images.pexels.com/photos/7947541/pexels-photo-7947541.jpeg?auto=compress&cs=tinysrgb&w=600',
    images: ['https://images.pexels.com/photos/7947541/pexels-photo-7947541.jpeg?auto=compress&cs=tinysrgb&w=600'],
    freelancer: flMap.alexdev,
    rating: 4.9,
    reviewCount: 52,
    ordersCount: 87,
    tags: ['React', 'TypeScript', 'Charts', 'Dashboard'],
    category: 'Frontend',
    categorySlug: 'frontend',
    isFeatured: true,
    packages: {
      economy: pkg('Эконом', 5000, 5, 'Базовый дашборд', ['3 виджета']),
      standard: pkg('Стандарт', 15000, 7, 'Полный дашборд', ['10 виджетов', 'Фильтры']),
      premium: pkg('Премиум', 30000, 14, 'Enterprise дашборд', ['Безлимит виджетов', 'Real-time']),
    },
  },
  {
    id: 'gig_4',
    title: 'Интеграция ChatGPT в ваш сайт или приложение',
    shortDescription: 'Подключу AI-чат на базе GPT-4',
    description: 'Интегрирую ChatGPT (GPT-4) в ваш сайт или приложение.',
    image: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=600',
    images: ['https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=600'],
    freelancer: flMap.aianna,
    rating: 5.0,
    reviewCount: 42,
    ordersCount: 67,
    tags: ['OpenAI', 'Python', 'React', 'API'],
    category: 'AI Интеграции',
    categorySlug: 'ai-integrations',
    isFeatured: true,
    packages: {
      economy: pkg('Эконом', 4000, 2, 'Базовая интеграция', ['Чат-виджет', 'GPT-3.5']),
      standard: pkg('Стандарт', 10000, 5, 'Продвинутая интеграция', ['GPT-4', 'Кастом промпты']),
      premium: pkg('Премиум', 25000, 10, 'RAG-система', ['RAG', 'База знаний', 'API']),
    },
  },
  {
    id: 'gig_5',
    title: 'Мобильное приложение на React Native',
    shortDescription: 'Кроссплатформенное приложение iOS + Android',
    description: 'Создам мобильное приложение для iOS и Android на React Native.',
    image: 'https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=600',
    images: ['https://images.pexels.com/photos/1092644/pexels-photo-1092644.jpeg?auto=compress&cs=tinysrgb&w=600'],
    freelancer: flMap.mobilenik,
    rating: 4.6,
    reviewCount: 38,
    ordersCount: 51,
    tags: ['React Native', 'TypeScript', 'iOS', 'Android'],
    category: 'Мобильные приложения',
    categorySlug: 'mobile-apps',
    isFeatured: false,
    packages: {
      economy: pkg('Эконом', 15000, 7, '3 экрана', ['3 экрана', 'iOS + Android']),
      standard: pkg('Стандарт', 40000, 14, '8 экранов', ['8 экранов', 'API', 'Push']),
      premium: pkg('Премиум', 80000, 30, 'Полное приложение', ['Безлимит экранов', 'Публикация']),
    },
  },
  {
    id: 'gig_6',
    title: 'Сверстаю макет из Figma в идеальный код',
    shortDescription: 'Pixel-perfect вёрстка по макету из Figma',
    description: 'Превращу ваш Figma-макет в чистый и адаптивный код.',
    image: 'https://images.pexels.com/photos/326503/pexels-photo-326503.jpeg?auto=compress&cs=tinysrgb&w=600',
    images: ['https://images.pexels.com/photos/326503/pexels-photo-326503.jpeg?auto=compress&cs=tinysrgb&w=600'],
    freelancer: flMap.marinaui,
    rating: 4.8,
    reviewCount: 89,
    ordersCount: 156,
    tags: ['HTML', 'CSS', 'React', 'Figma'],
    category: 'Frontend',
    categorySlug: 'frontend',
    isFeatured: false,
    packages: {
      economy: pkg('Эконом', 1500, 2, '1 страница', ['1 страница', 'Адаптивность']),
      standard: pkg('Стандарт', 4000, 4, 'До 5 страниц', ['5 страниц', 'React', 'Анимации']),
      premium: pkg('Премиум', 10000, 7, 'Полный сайт', ['Безлимит страниц', 'CMS', 'SEO']),
    },
  },
  {
    id: 'gig_7',
    title: 'REST API + база данных на Node.js',
    shortDescription: 'Разработка серверной части с API и PostgreSQL',
    description: 'Спроектирую и разработаю REST API с чистой архитектурой.',
    image: 'https://images.pexels.com/photos/1181677/pexels-photo-1181677.jpeg?auto=compress&cs=tinysrgb&w=600',
    images: ['https://images.pexels.com/photos/1181677/pexels-photo-1181677.jpeg?auto=compress&cs=tinysrgb&w=600'],
    freelancer: flMap.backendpro,
    rating: 4.8,
    reviewCount: 71,
    ordersCount: 112,
    tags: ['Node.js', 'PostgreSQL', 'Express', 'Docker'],
    category: 'Backend',
    categorySlug: 'backend',
    isFeatured: false,
    packages: {
      economy: pkg('Эконом', 5000, 3, 'Простой API', ['5 эндпоинтов', 'Auth']),
      standard: pkg('Стандарт', 15000, 7, 'Полный API', ['15 эндпоинтов', 'Документация']),
      premium: pkg('Премиум', 35000, 14, 'Микросервисы', ['Docker', 'CI/CD', 'Мониторинг']),
    },
  },
  {
    id: 'gig_8',
    title: 'MVP за 3 дня — от идеи до рабочего прототипа',
    shortDescription: 'Быстрый запуск вашего продукта с помощью вайб-кодинга',
    description: 'Помогу превратить вашу идею в рабочий MVP за 3 дня.',
    image: 'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=600',
    images: ['https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=600'],
    freelancer: flMap.alexdev,
    rating: 4.9,
    reviewCount: 34,
    ordersCount: 45,
    tags: ['React', 'Next.js', 'Supabase', 'AI'],
    category: 'Вайб-кодинг MVP',
    categorySlug: 'mvp',
    isFeatured: true,
    packages: {
      economy: pkg('Эконом', 10000, 3, 'Базовый MVP', ['3 страницы', 'Auth']),
      standard: pkg('Стандарт', 30000, 5, 'Продвинутый MVP', ['7 страниц', 'API', 'Деплой']),
      premium: pkg('Премиум', 60000, 10, 'Production MVP', ['Полный продукт', 'CI/CD']),
    },
  },
  {
    id: 'gig_9',
    title: 'Настрою базу данных PostgreSQL + Supabase',
    shortDescription: 'Проектирование БД, миграции, RLS',
    description: 'Спроектирую оптимальную структуру базы данных.',
    image: 'https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&cs=tinysrgb&w=600',
    images: ['https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg?auto=compress&cs=tinysrgb&w=600'],
    freelancer: flMap.datamagic,
    rating: 4.7,
    reviewCount: 33,
    ordersCount: 45,
    tags: ['PostgreSQL', 'Supabase', 'SQL', 'Redis'],
    category: 'Базы данных',
    categorySlug: 'databases',
    isFeatured: false,
    packages: {
      economy: pkg('Эконом', 3000, 2, 'Базовая настройка', ['Схема БД', '5 таблиц']),
      standard: pkg('Стандарт', 8000, 4, 'Полная настройка', ['15 таблиц', 'RLS', 'Индексы']),
      premium: pkg('Премиум', 18000, 7, 'Enterprise', ['Оптимизация', 'Репликация']),
    },
  },
];

export const MOCK_REVIEWS: Review[] = [
  { id: 'rev_1', author: 'Олег Тимофеев', avatar: 'https://images.pexels.com/photos/1043471/pexels-photo-1043471.jpeg?auto=compress&cs=tinysrgb&w=80', rating: 5, text: 'Лендинг получился невероятный! Скорость загрузки — огонь, дизайн точно по макету. Рекомендую!', date: '2 дн назад', reply: 'Спасибо за отзыв!' },
  { id: 'rev_2', author: 'Виктория Белова', avatar: 'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=80', rating: 5, text: 'Бот для нашего магазина работает идеально. Клиенты довольны.', date: '5 дн назад' },
  { id: 'rev_3', author: 'Максим Горбунов', avatar: 'https://images.pexels.com/photos/1516680/pexels-photo-1516680.jpeg?auto=compress&cs=tinysrgb&w=80', rating: 4, text: 'Хороший дашборд, всё работает. В целом доволен.', date: '1 нед назад', reply: 'Спасибо! Дополнительные графики можно добавить.' },
  { id: 'rev_4', author: 'Анастасия Юрьева', avatar: 'https://images.pexels.com/photos/1587009/pexels-photo-1587009.jpeg?auto=compress&cs=tinysrgb&w=80', rating: 5, text: 'AI-чат на сайте — это просто магия!', date: '3 дн назад' },
  { id: 'rev_5', author: 'Сергей Павлов', avatar: 'https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&w=80', rating: 5, text: 'MVP готов за 3 дня, как и обещали. Вайб-кодинг — будущее!', date: '1 дн назад' },
  { id: 'rev_6', author: 'Наталья Ким', avatar: 'https://images.pexels.com/photos/1065084/pexels-photo-1065084.jpeg?auto=compress&cs=tinysrgb&w=80', rating: 4, text: 'Вёрстка pixel-perfect, всё по макету. Буду обращаться ещё.', date: '4 дн назад' },
];
