#!/usr/bin/env node
/**
 * Seed VibeCoder with rich demo data + real photos
 * Run: node scripts/seed-rich.js
 */
const sdk = require('node-appwrite');
const client = new sdk.Client()
  .setEndpoint('https://appwrite.vibecoding.by/v1')
  .setProject('69aa2114000211b48e63')
  .setKey('standard_06b8634032f75c7d02d49e7a4add952c4183146ce5def3dc0f4a9df7e18307b29193788a0aa7694e6146ac3339a99eae5de4c3ce24b6a284e41f84dad5683cbc9a60ab5b18084171ad9b9a60d470bbce068b4ee21c8231467bd92bec43c9ed9dcfbe6e23f784c4c77e0c88beeacb60f4a7873f2baa936246a7aa4bacbd3c0d57');
const db = new sdk.Databases(client);
const DB = 'vibecoding';

const img = (id) => `https://images.unsplash.com/photo-${id}?w=800&h=450&fit=crop&q=80`;
const avatar = (q) => `https://images.unsplash.com/${q}`;

const PROFILES = [
  { id: 'prof_alex', user_id: 'user_alex', username: 'alexdev', name: 'Александр Петров', avatar: avatar('photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop'), title: 'Full-Stack AI Developer', rating: 4.9, review_count: 127, orders_completed: 253, response_time: '~30 мин', is_online: true, location: 'Москва', member_since: 'январь 2024', bio: 'Senior разработчик с 8+ лет опыта. Специализируюсь на React, Next.js, AI интеграциях. Создал 50+ MVP для стартапов. Использую Cursor, Claude, Copilot для максимальной скорости.', skills: JSON.stringify(['React', 'Next.js', 'TypeScript', 'Python', 'OpenAI', 'Claude API', 'Cursor', 'Supabase']), success_rate: 98, level: 'pro', role: 'freelancer', balance: 0 },
  { id: 'prof_marina', user_id: 'user_marina', username: 'marinaui', name: 'Марина Козлова', avatar: avatar('photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop'), title: 'UI/UX & Frontend', rating: 4.8, review_count: 89, orders_completed: 156, response_time: '~1 час', is_online: true, location: 'Санкт-Петербург', member_since: 'март 2024', bio: 'Создаю красивые и функциональные интерфейсы. Figma → React за 2 дня. AI-assisted дизайн с Midjourney и v0.', skills: JSON.stringify(['Figma', 'React', 'Tailwind', 'v0', 'Midjourney', 'Framer Motion']), success_rate: 97, level: 'pro', role: 'freelancer', balance: 0 },
  { id: 'prof_dmitry', user_id: 'user_dmitry', username: 'botmaster', name: 'Дмитрий Волков', avatar: avatar('photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop'), title: 'Telegram & AI Bots', rating: 4.7, review_count: 64, orders_completed: 98, response_time: '~2 часа', is_online: false, location: 'Казань', member_since: 'февраль 2024', bio: 'Разрабатываю Telegram ботов с AI. GPT-боты для бизнеса, RAG системы, автоматизация. 100+ ботов в продакшене.', skills: JSON.stringify(['Python', 'aiogram', 'OpenAI', 'LangChain', 'RAG', 'PostgreSQL', 'Docker']), success_rate: 95, level: 'verified', role: 'freelancer', balance: 0 },
  { id: 'prof_anna', user_id: 'user_anna', username: 'aianna', name: 'Анна Сергеева', avatar: avatar('photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop'), title: 'AI/ML Engineer', rating: 5.0, review_count: 42, orders_completed: 67, response_time: '~1 час', is_online: true, location: 'Новосибирск', member_since: 'апрель 2024', bio: 'Machine Learning инженер. Fine-tuning LLM, RAG системы, компьютерное зрение. Kaggle Master.', skills: JSON.stringify(['Python', 'PyTorch', 'TensorFlow', 'LangChain', 'OpenAI', 'Claude', 'RAG', 'Vector DB']), success_rate: 100, level: 'pro', role: 'freelancer', balance: 0 },
  { id: 'prof_nikolay', user_id: 'user_nikolay', username: 'mobilenik', name: 'Николай Ростов', avatar: avatar('photo-1500648767791-00dcc994a43e?w=200&h=200&fit=crop'), title: 'Mobile & Cross-platform', rating: 4.6, review_count: 51, orders_completed: 78, response_time: '~3 часа', is_online: false, location: 'Екатеринбург', member_since: 'май 2024', bio: 'React Native и Flutter разработчик. Создаю мобильные приложения с AI-функциями. Публикация в App Store и Google Play.', skills: JSON.stringify(['React Native', 'Flutter', 'TypeScript', 'Firebase', 'Expo']), success_rate: 94, level: 'verified', role: 'freelancer', balance: 0 },
  { id: 'prof_elena', user_id: 'user_elena', username: 'webdesigner', name: 'Елена Морозова', avatar: avatar('photo-1544005313-94ddf0286df2?w=200&h=200&fit=crop'), title: 'Web Design & Branding', rating: 4.9, review_count: 73, orders_completed: 189, response_time: '~45 мин', is_online: true, location: 'Краснодар', member_since: 'январь 2024', bio: 'Создаю лендинги, корпоративные сайты и фирменные стили. AI-генерация графики через Midjourney и DALL-E.', skills: JSON.stringify(['Figma', 'Webflow', 'Photoshop', 'Midjourney', 'DALL-E', 'Illustrator']), success_rate: 99, level: 'pro', role: 'freelancer', balance: 0 },
  { id: 'prof_igor_b', user_id: 'user_igor_b', username: 'backendpro', name: 'Игорь Кузнецов', avatar: avatar('photo-1506794778202-cad84cf45f1d?w=200&h=200&fit=crop'), title: 'Backend & DevOps', rating: 4.8, review_count: 56, orders_completed: 112, response_time: '~1 час', is_online: true, location: 'Москва', member_since: 'февраль 2024', bio: 'Backend на Node.js, Python, Go. DevOps: Docker, Kubernetes, CI/CD. Настройка серверов, деплой, мониторинг.', skills: JSON.stringify(['Node.js', 'Python', 'Go', 'Docker', 'Kubernetes', 'AWS', 'PostgreSQL']), success_rate: 96, level: 'verified', role: 'freelancer', balance: 0 },
  { id: 'prof_pavel', user_id: 'user_pavel', username: 'datamagic', name: 'Павел Новиков', avatar: avatar('photo-1519085360753-af0119f7cbe7?w=200&h=200&fit=crop'), title: 'Data & Automation', rating: 4.7, review_count: 38, orders_completed: 45, response_time: '~2 часа', is_online: false, location: 'Самара', member_since: 'июнь 2024', bio: 'Автоматизация бизнес-процессов с AI. Парсинг, скрапинг, интеграции API. Make, Zapier, n8n + кастомные решения.', skills: JSON.stringify(['Python', 'n8n', 'Make', 'Zapier', 'API', 'Selenium', 'BeautifulSoup']), success_rate: 93, level: 'verified', role: 'freelancer', balance: 0 },
  { id: 'prof_sofia', user_id: 'user_sofia', username: 'sofiacode', name: 'София Белова', avatar: avatar('photo-1487412720507-e7ab37603c6f?w=200&h=200&fit=crop'), title: 'Vibe-coder & AI Builder', rating: 4.9, review_count: 31, orders_completed: 52, response_time: '~30 мин', is_online: true, location: 'Москва', member_since: 'август 2024', bio: 'Создаю сайты и приложения через вайб-кодинг. Cursor + Claude + v0 = MVP за 1-3 дня. Быстро, красиво, дёшево.', skills: JSON.stringify(['Cursor', 'Claude', 'v0', 'Bolt', 'React', 'Next.js', 'Tailwind']), success_rate: 98, level: 'pro', role: 'freelancer', balance: 0 },
  { id: 'prof_artem', user_id: 'user_artem', username: 'artemai', name: 'Артём Лебедев', avatar: avatar('photo-1463453091185-61582044d556?w=200&h=200&fit=crop'), title: 'AI Agent Developer', rating: 4.8, review_count: 22, orders_completed: 34, response_time: '~1 час', is_online: true, location: 'Минск', member_since: 'сентябрь 2024', bio: 'Разрабатываю AI-агентов для бизнеса. CrewAI, AutoGPT, LangGraph. Автоматизация рутины через интеллектуальных ботов.', skills: JSON.stringify(['Python', 'LangChain', 'CrewAI', 'LangGraph', 'OpenAI', 'Claude', 'Pinecone']), success_rate: 97, level: 'verified', role: 'freelancer', balance: 0 },
];

const GIGS = [
  { id: 'gig_1', title: 'Создам MVP вашего SaaS за 3 дня на Next.js + AI', description: 'Полноценный MVP с авторизацией, дашбордом, API. Использую Cursor + Claude для максимальной скорости. Stack: Next.js 14, Tailwind, Supabase, Stripe.', short_description: 'MVP SaaS за 3 дня', image: img('1460925895917-afdab827c52f'), freelancer_id: 'user_alex', freelancer_name: 'Александр Петров', freelancer_username: 'alexdev', rating: 4.9, review_count: 52, orders_count: 87, tags: JSON.stringify(['Next.js', 'React', 'Supabase', 'AI', 'MVP', 'Cursor']), category: 'Вайб-кодинг MVP', category_slug: 'mvp', is_featured: true, status: 'active', package_economy: JSON.stringify({ name: 'Лендинг', price: 5000, deliveryDays: 1, description: 'Одностраничник', features: ['1 страница', 'Адаптив', 'Деплой'] }), package_standard: JSON.stringify({ name: 'MVP', price: 15000, deliveryDays: 3, description: 'Полный MVP', features: ['До 5 страниц', 'Авторизация', 'БД', 'API', 'Деплой'] }), package_premium: JSON.stringify({ name: 'SaaS', price: 40000, deliveryDays: 7, description: 'Полный SaaS', features: ['Безлимит страниц', 'Подписки', 'Stripe', 'Админка', 'AI функции'] }) },
  { id: 'gig_2', title: 'Разработаю Telegram бота с ChatGPT / Claude', description: 'Умный Telegram бот для вашего бизнеса. Отвечает на вопросы клиентов, принимает заказы, интеграция с CRM. Обучение на ваших данных через RAG.', short_description: 'AI Telegram бот', image: img('1611746872915-64382b5c76da'), freelancer_id: 'user_dmitry', freelancer_name: 'Дмитрий Волков', freelancer_username: 'botmaster', rating: 4.7, review_count: 34, orders_count: 56, tags: JSON.stringify(['Telegram', 'ChatGPT', 'Python', 'AI', 'Bot', 'RAG']), category: 'Боты и автоматизация', category_slug: 'bots-automation', is_featured: true, status: 'active', package_economy: JSON.stringify({ name: 'Простой бот', price: 3000, deliveryDays: 2, description: 'Базовый бот', features: ['Команды', 'Кнопки', 'Деплой'] }), package_standard: JSON.stringify({ name: 'AI бот', price: 8000, deliveryDays: 4, description: 'Бот с AI', features: ['ChatGPT интеграция', 'Память диалога', 'Админ-панель'] }), package_premium: JSON.stringify({ name: 'RAG бот', price: 20000, deliveryDays: 7, description: 'Умный бот', features: ['RAG на ваших данных', 'Обучение', 'CRM интеграция', 'Аналитика'] }) },
  { id: 'gig_3', title: 'Интеграция ChatGPT / Claude API в ваш продукт', description: 'Внедрю AI в ваше приложение. Чат-бот поддержки, генерация контента, анализ данных, суммаризация. Любые LLM: OpenAI, Anthropic, Mistral.', short_description: 'AI интеграция', image: img('1677442136019-21780ecad995'), freelancer_id: 'user_anna', freelancer_name: 'Анна Сергеева', freelancer_username: 'aianna', rating: 5.0, review_count: 42, orders_count: 67, tags: JSON.stringify(['OpenAI', 'Claude', 'API', 'AI', 'LangChain', 'Python']), category: 'AI Интеграции', category_slug: 'ai-integrations', is_featured: true, status: 'active', package_economy: JSON.stringify({ name: 'Базовая', price: 4000, deliveryDays: 2, description: 'Простая интеграция', features: ['1 AI функция', 'API ключ', 'Документация'] }), package_standard: JSON.stringify({ name: 'Продвинутая', price: 12000, deliveryDays: 5, description: 'Комплексная', features: ['До 5 AI функций', 'Streaming', 'Rate limiting', 'Кеширование'] }), package_premium: JSON.stringify({ name: 'Enterprise', price: 30000, deliveryDays: 10, description: 'Полная интеграция', features: ['Безлимит функций', 'RAG', 'Fine-tuning', 'Мониторинг', 'SLA'] }) },
  { id: 'gig_4', title: 'Создам лендинг на Next.js за 2 дня', description: 'Современный, быстрый лендинг с анимациями. SEO-оптимизация, мобильная адаптация, подключение аналитики. Дизайн через v0 + Cursor.', short_description: 'Лендинг за 2 дня', image: img('1547658719-da2b51169166'), freelancer_id: 'user_alex', freelancer_name: 'Александр Петров', freelancer_username: 'alexdev', rating: 4.9, review_count: 27, orders_count: 45, tags: JSON.stringify(['Next.js', 'React', 'Landing', 'SEO', 'v0', 'Cursor']), category: 'Разработка сайтов', category_slug: 'web-development', is_featured: true, status: 'active', package_economy: JSON.stringify({ name: 'Лендинг', price: 2000, deliveryDays: 1, description: 'Одна страница', features: ['1 секция hero', 'Адаптив', 'SEO'] }), package_standard: JSON.stringify({ name: 'Мульти', price: 5000, deliveryDays: 2, description: 'Полный лендинг', features: ['5-7 секций', 'Анимации', 'Форма', 'SEO', 'Деплой'] }), package_premium: JSON.stringify({ name: 'Премиум', price: 12000, deliveryDays: 4, description: 'Лендинг+CRM', features: ['10+ секций', 'CRM интеграция', 'A/B тесты', 'Аналитика', 'Поддержка 30 дней'] }) },
  { id: 'gig_5', title: 'UI/UX дизайн мобильного приложения в Figma', description: 'Создам полный дизайн вашего приложения. Wireframes, UI Kit, прототип, анимации. Современный стиль с AI-assisted дизайном.', short_description: 'Дизайн приложения', image: img('1512941937-f5c62a4e3a1e'), freelancer_id: 'user_marina', freelancer_name: 'Марина Козлова', freelancer_username: 'marinaui', rating: 4.8, review_count: 38, orders_count: 62, tags: JSON.stringify(['Figma', 'UI/UX', 'Mobile', 'Design', 'Midjourney']), category: 'Мобильные приложения', category_slug: 'mobile-apps', is_featured: true, status: 'active', package_economy: JSON.stringify({ name: 'Wireframe', price: 3000, deliveryDays: 2, description: 'Каркас', features: ['5 экранов', 'Wireframes', 'Гайд'] }), package_standard: JSON.stringify({ name: 'Дизайн', price: 10000, deliveryDays: 5, description: 'Полный дизайн', features: ['10 экранов', 'UI Kit', 'Прототип', 'Гайд'] }), package_premium: JSON.stringify({ name: 'Премиум', price: 25000, deliveryDays: 10, description: 'Всё включено', features: ['20+ экранов', 'UI Kit', 'Анимации', 'Прототип', 'Дизайн-система'] }) },
  { id: 'gig_6', title: 'React дашборд с графиками и аналитикой', description: 'Создам интерактивный дашборд для вашего бизнеса. Recharts, D3.js, real-time данные, фильтры, экспорт в PDF.', short_description: 'React дашборд', image: img('1551288049-bebda4e38f71'), freelancer_id: 'user_alex', freelancer_name: 'Александр Петров', freelancer_username: 'alexdev', rating: 4.9, review_count: 21, orders_count: 35, tags: JSON.stringify(['React', 'TypeScript', 'Dashboard', 'Charts', 'D3.js']), category: 'Frontend', category_slug: 'frontend', is_featured: false, status: 'active', package_economy: JSON.stringify({ name: 'Базовый', price: 5000, deliveryDays: 3, description: '3 виджета', features: ['3 графика', 'Фильтры', 'Адаптив'] }), package_standard: JSON.stringify({ name: 'Бизнес', price: 15000, deliveryDays: 5, description: '10 виджетов', features: ['10 графиков', 'Real-time', 'Экспорт PDF', 'Dark mode'] }), package_premium: JSON.stringify({ name: 'Enterprise', price: 35000, deliveryDays: 10, description: 'Полный дашборд', features: ['Безлимит виджетов', 'Drag & drop', 'API', 'Роли доступа'] }) },
  { id: 'gig_7', title: 'Настрою CI/CD, Docker, деплой на VPS', description: 'Полная настройка DevOps: Docker Compose, GitHub Actions, Nginx, SSL, мониторинг. Автодеплой при push в git.', short_description: 'DevOps настройка', image: img('1558494949-ef010cbdcc31'), freelancer_id: 'user_igor_b', freelancer_name: 'Игорь Кузнецов', freelancer_username: 'backendpro', rating: 4.8, review_count: 29, orders_count: 48, tags: JSON.stringify(['Docker', 'DevOps', 'CI/CD', 'Nginx', 'Linux', 'GitHub Actions']), category: 'Backend', category_slug: 'backend', is_featured: false, status: 'active', package_economy: JSON.stringify({ name: 'Деплой', price: 2000, deliveryDays: 1, description: 'Настройка VPS', features: ['Docker', 'Nginx', 'SSL'] }), package_standard: JSON.stringify({ name: 'CI/CD', price: 6000, deliveryDays: 3, description: 'Автодеплой', features: ['Docker Compose', 'GitHub Actions', 'Мониторинг'] }), package_premium: JSON.stringify({ name: 'Full DevOps', price: 15000, deliveryDays: 5, description: 'Полная инфра', features: ['Kubernetes', 'Логирование', 'Бэкапы', 'Мониторинг', 'Alerts'] }) },
  { id: 'gig_8', title: 'AI-агент для автоматизации бизнеса', description: 'Разработаю AI-агента который будет выполнять рутинные задачи: обработка email, заполнение CRM, генерация отчётов, анализ данных.', short_description: 'AI агент', image: img('1620712943543-bcc4688e7485'), freelancer_id: 'user_artem', freelancer_name: 'Артём Лебедев', freelancer_username: 'artemai', rating: 4.8, review_count: 18, orders_count: 28, tags: JSON.stringify(['AI', 'Agent', 'CrewAI', 'LangChain', 'Automation', 'Python']), category: 'AI Интеграции', category_slug: 'ai-integrations', is_featured: true, status: 'active', package_economy: JSON.stringify({ name: 'Простой', price: 5000, deliveryDays: 3, description: '1 задача', features: ['1 автоматизация', 'Деплой', 'Документация'] }), package_standard: JSON.stringify({ name: 'Комплекс', price: 15000, deliveryDays: 7, description: 'Мульти-агент', features: ['3 автоматизации', 'Интеграция с API', 'Мониторинг'] }), package_premium: JSON.stringify({ name: 'Enterprise', price: 40000, deliveryDays: 14, description: 'Полная система', features: ['Безлимит задач', 'Обучение', 'Поддержка 30 дней', 'SLA'] }) },
  { id: 'gig_9', title: 'Сайт на Cursor + Claude за 1 день', description: 'Вайб-кодинг в действии! Создам сайт любой сложности используя AI-инструменты. Результат за 1-3 дня вместо недель.', short_description: 'Вайб-кодинг сайт', image: img('1555066931-4365d14bab8c'), freelancer_id: 'user_sofia', freelancer_name: 'София Белова', freelancer_username: 'sofiacode', rating: 4.9, review_count: 28, orders_count: 44, tags: JSON.stringify(['Cursor', 'Claude', 'v0', 'Bolt', 'React', 'Vibe-coding']), category: 'Вайб-кодинг MVP', category_slug: 'mvp', is_featured: true, status: 'active', package_economy: JSON.stringify({ name: 'Мини', price: 1500, deliveryDays: 1, description: '1 страница', features: ['Лендинг', 'Адаптив', 'Деплой'] }), package_standard: JSON.stringify({ name: 'Стандарт', price: 5000, deliveryDays: 2, description: 'Полный сайт', features: ['3-5 страниц', 'Анимации', 'Формы', 'SEO'] }), package_premium: JSON.stringify({ name: 'Полный', price: 12000, deliveryDays: 3, description: 'Сложный проект', features: ['10+ страниц', 'БД', 'Авторизация', 'Админка'] }) },
  { id: 'gig_10', title: 'Парсинг данных и автоматизация с AI', description: 'Автоматизирую сбор данных с любых сайтов. Парсинг, API интеграции, обработка через AI, выгрузка в Google Sheets / CRM.', short_description: 'Парсинг и автоматизация', image: img('1504868584819-f8e8b4b6d7e3'), freelancer_id: 'user_pavel', freelancer_name: 'Павел Новиков', freelancer_username: 'datamagic', rating: 4.7, review_count: 22, orders_count: 38, tags: JSON.stringify(['Python', 'Parsing', 'AI', 'Automation', 'API', 'n8n']), category: 'Боты и автоматизация', category_slug: 'bots-automation', is_featured: false, status: 'active', package_economy: JSON.stringify({ name: 'Простой', price: 2000, deliveryDays: 1, description: '1 источник', features: ['1 сайт', 'CSV выгрузка'] }), package_standard: JSON.stringify({ name: 'Продвинутый', price: 6000, deliveryDays: 3, description: '5 источников', features: ['5 сайтов', 'Google Sheets', 'Расписание'] }), package_premium: JSON.stringify({ name: 'Комплекс', price: 15000, deliveryDays: 5, description: 'Полная система', features: ['Безлимит', 'AI обработка', 'CRM', 'Мониторинг'] }) },
  { id: 'gig_11', title: 'RAG система на ваших документах', description: 'Создам систему вопрос-ответ на базе ваших документов. PDF, Word, сайт → вектор БД → умный поиск с AI. Идеально для баз знаний.', short_description: 'RAG система', image: img('1633356122544-f134324a6cee'), freelancer_id: 'user_anna', freelancer_name: 'Анна Сергеева', freelancer_username: 'aianna', rating: 5.0, review_count: 15, orders_count: 23, tags: JSON.stringify(['RAG', 'LangChain', 'OpenAI', 'Pinecone', 'Python', 'AI']), category: 'AI Интеграции', category_slug: 'ai-integrations', is_featured: true, status: 'active', package_economy: JSON.stringify({ name: 'Базовая', price: 8000, deliveryDays: 3, description: 'Простая RAG', features: ['До 50 документов', 'Веб-интерфейс', 'Деплой'] }), package_standard: JSON.stringify({ name: 'Бизнес', price: 20000, deliveryDays: 7, description: 'Продвинутая', features: ['500 документов', 'API', 'Гибридный поиск', 'Аналитика'] }), package_premium: JSON.stringify({ name: 'Enterprise', price: 50000, deliveryDays: 14, description: 'Enterprise RAG', features: ['Безлимит', 'Мульти-модель', 'Роли доступа', 'SLA', 'Поддержка'] }) },
  { id: 'gig_12', title: 'Мобильное приложение на React Native', description: 'Кроссплатформенное приложение для iOS и Android. Публикация в App Store и Google Play. Push-уведомления, оффлайн режим.', short_description: 'React Native приложение', image: img('1512941937-f5c62a4e3a1e'), freelancer_id: 'user_nikolay', freelancer_name: 'Николай Ростов', freelancer_username: 'mobilenik', rating: 4.6, review_count: 24, orders_count: 38, tags: JSON.stringify(['React Native', 'iOS', 'Android', 'Mobile', 'Expo']), category: 'Мобильные приложения', category_slug: 'mobile-apps', is_featured: false, status: 'active', package_economy: JSON.stringify({ name: 'Прототип', price: 10000, deliveryDays: 5, description: 'MVP', features: ['3 экрана', 'Навигация', 'API'] }), package_standard: JSON.stringify({ name: 'Приложение', price: 30000, deliveryDays: 14, description: 'Полное', features: ['10 экранов', 'Push', 'Оффлайн', 'Публикация'] }), package_premium: JSON.stringify({ name: 'Премиум', price: 60000, deliveryDays: 30, description: 'Сложное', features: ['20+ экранов', 'Чат', 'Оплата', 'Аналитика', 'Поддержка'] }) },
];

const REVIEWS = [
  { id: 'rev_1', gig_id: 'gig_1', order_id: 'order_1', author_id: 'user_client1', author_name: 'Михаил К.', author_avatar: avatar('1535713875002-d1d0cf377fde'), rating: 5, text: 'Невероятная скорость! MVP был готов за 2 дня. Всё работает отлично, код чистый. Александр — настоящий профи вайб-кодинга.', reply: 'Спасибо, Михаил! Было приятно работать над вашим проектом. Обращайтесь ещё!' },
  { id: 'rev_2', gig_id: 'gig_2', order_id: 'order_2', author_id: 'user_client2', author_name: 'Ольга С.', author_avatar: avatar('1544005313-94ddf0286df2'), rating: 5, text: 'Бот работает как часы! Клиенты довольны, что получают мгновенные ответы. RAG на наших документах — это магия.', reply: '' },
  { id: 'rev_3', gig_id: 'gig_3', order_id: 'order_3', author_id: 'user_client3', author_name: 'Андрей Т.', author_avatar: avatar('1507003211169-0a1dd7228f2d'), rating: 5, text: 'Анна интегрировала Claude API в наш продукт за 3 дня. Качество ответов AI превзошло ожидания. Рекомендую!', reply: 'Благодарю за отзыв! Рада что интеграция работает стабильно.' },
  { id: 'rev_4', gig_id: 'gig_9', order_id: 'order_4', author_id: 'user_client4', author_name: 'Екатерина Р.', author_avatar: avatar('1438761681033-6461ffad8d80'), rating: 5, text: 'София сделала мне потрясающий лендинг за 1 день! Вайб-кодинг — это будущее. Цена смешная для такого качества.', reply: '' },
  { id: 'rev_5', gig_id: 'gig_4', order_id: 'order_5', author_id: 'user_client5', author_name: 'Дмитрий П.', author_avatar: avatar('1472099645785-5658abf4ff4e'), rating: 4, text: 'Хороший лендинг, всё по ТЗ. Были небольшие правки по дизайну, но всё исправили быстро.', reply: 'Спасибо за фидбэк! Всегда готов доработать.' },
  { id: 'rev_6', gig_id: 'gig_8', order_id: 'order_6', author_id: 'user_client6', author_name: 'Наталья М.', author_avatar: avatar('1487412720507-e7ab37603c6f'), rating: 5, text: 'AI-агент автоматизировал обработку email — экономим 3 часа в день! Артём отлично разобрался в нашем бизнесе.', reply: '' },
  { id: 'rev_7', gig_id: 'gig_11', order_id: 'order_7', author_id: 'user_client7', author_name: 'Сергей В.', author_avatar: avatar('1500648767791-00dcc994a43e'), rating: 5, text: 'RAG система работает идеально. Загрузили 200 документов — поиск мгновенный, ответы точные. Лучшая инвестиция.', reply: 'Рада помочь! Если понадобится расширение — пишите.' },
  { id: 'rev_8', gig_id: 'gig_1', order_id: 'order_8', author_id: 'user_client8', author_name: 'Алексей И.', author_avatar: avatar('1506794778202-cad84cf45f1d'), rating: 5, text: 'Заказал SaaS пакет. Получил полноценную платформу с подписками и админкой за неделю. Cursor + Claude = космос.', reply: '' },
];

async function seed(collectionId, items, name) {
  console.log(`\n📦 ${name} (${items.length})`);
  try {
    const { documents } = await db.listDocuments(DB, collectionId, [sdk.Query.limit(100)]);
    for (const doc of documents) await db.deleteDocument(DB, collectionId, doc.$id);
    console.log(`  🗑️  Cleared ${documents.length}`);
  } catch {}
  let ok = 0, fail = 0;
  for (const item of items) {
    const { id, ...data } = item;
    try {
      await db.createDocument(DB, collectionId, id, data, [sdk.Permission.read(sdk.Role.any()), sdk.Permission.update(sdk.Role.users()), sdk.Permission.delete(sdk.Role.users())]);
      ok++;
    } catch (e) { console.log(`  ❌ ${id}: ${e.message?.slice(0, 80)}`); fail++; }
  }
  console.log(`  ✅ ${ok} created, ${fail} failed`);
}

async function main() {
  console.log('🌱 Seeding VibeCoder with rich demo data...');
  await seed('fl_profiles', PROFILES, 'Profiles');
  await seed('fl_gigs', GIGS, 'Gigs');
  await seed('fl_reviews', REVIEWS, 'Reviews');
  console.log('\n✅ Done!');
}
main().catch(console.error);
